export const SIGNUP_STEP_1_SUBMIT = "SIGNUP_STEP_1_SUBMIT"
export const FETCH_SECURITY_QUESTIONS = "FETCH_SECURITY_QUESTIONS"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_SUBMIT = "SIGNUP_SUBMIT"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"
export const RESET_ERROR = "RESET_ERROR"


